---
name: lint

env:
  DEVBOX_VERSION: ${{ vars.DEVBOX_VERSION }}
  DEVBOX_USE_VERSION: ${{ vars.DEVBOX_VERSION }}

defaults:
  run:
    working-directory: "pokerops.gluster_repo"

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4
        with:
          path: "pokerops.gluster_repo"

      - name: Generate devbox locale
        run: sudo locale-gen C.UTF-8

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.12.0
        with:
          project-path: "pokerops.gluster_repo"

      - name: Lint code
        run: devbox run -- make lint
