---
# Test CI trigger
name: lint

env:
  DEVBOX_VERSION: ${{ vars.DEVBOX_VERSION }}

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4
        with:
          path: "pokerops.gluster_repo"

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.12.0
        with:
          project-path: "pokerops.gluster_repo"
          devbox-version: ${{ vars.DEVBOX_VERSION }}

      - name: Lint code
        run: devbox run -- make lint
