---
name: molecule

env:
  DEVBOX_VERSION: ${{ vars.DEVBOX_VERSION }}

on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 5 * * 5"

defaults:
  run:
    working-directory: "pokerops.gluster_repo"

jobs:
  molecule:
    name: molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scenario:
          - name: default
        image:
          - name: ubuntu2204
            command: /lib/systemd/systemd
          - name: ubuntu2004
            command: /lib/systemd/systemd
          - name: debian12
            command: /lib/systemd/systemd
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4
        with:
          path: "pokerops.gluster_repo"

      - name: Generate devbox locale
        run: sudo locale-gen C.UTF-8

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.14.2
        with:
          project-path: "pokerops.gluster_repo"

      - name: Debug test environment
        run: devbox run -- make debug

      - name: Run molecule tests.
        run: devbox run make test
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_DOCKER_IMAGE: ${{ matrix.image.name }}
          MOLECULE_DOCKER_COMMAND: ${{ matrix.image.command }}
          MOLECULE_SCENARIO: ${{ matrix.scenario.name }}
